import { EditorView } from '@codemirror/view';

// Layout-only rules shared by every theme, so the editor fills its container.
export const baseTheme = EditorView.baseTheme({
	'&': {
		height: '100%',
	},
	'.cm-scroller': {
		flex: '1',
		overflow: 'auto',
	},
	'.cm-selectionLayer': {
		zIndex: '-1 !important',
	},
	'.chord-search-panel': {
		position: 'absolute',
		top: '0.4rem',
		right: '0.5rem',
		zIndex: '20',
		pointerEvents: 'auto',
		display: 'flex',
		width: 'min(100% - 1rem, 32rem)',
		margin: '0',
		border: '1px solid var(--color-neutral-700, #3f3f46)',
		borderRadius: '0.45rem',
		boxShadow: '0 0.5rem 1.25rem color-mix(in oklch, #000 28%, transparent)',
		flexWrap: 'wrap',
		alignItems: 'center',
		gap: '0.3rem',
		padding: '0.35rem 0.45rem',
		borderBottom: '1px solid var(--color-neutral-200, #e4e4e7)',
		backgroundColor: 'var(--color-white, #ffffff)',
		fontSize: '0.875rem',
	},
	'.chord-search-controls': {
		display: 'flex',
		flex: '1 1 100%',
		flexWrap: 'nowrap',
		alignItems: 'center',
		gap: '0.25rem',
	},
	'.chord-search-navigation': {
		display: 'flex',
		flex: '0 0 auto',
		alignItems: 'center',
		gap: '0.2rem',
	},
	'.chord-search-fields': {
		display: 'flex',
		flex: '1 1 auto',
		minWidth: '0',
		flexDirection: 'column',
		gap: '0.25rem',
	},
	'.chord-search-replace-row': {
		display: 'flex',
		flex: '1 1 100%',
		flexWrap: 'nowrap',
		alignItems: 'center',
		gap: '0.25rem',
	},
	'.chord-search-replace-row[hidden]': {
		display: 'none',
	},
	'.chord-search-field': {
		flex: '1 1 12rem',
		border: '1px solid var(--color-neutral-300, #d4d4d8)',
		borderRadius: '0.35rem',
		backgroundColor: 'var(--color-white, #ffffff)',
	},
	'.chord-search-match-count': {
		flex: '0 0 auto',
		minWidth: '3.5rem',
		color: 'var(--color-neutral-500, #71717a)',
		fontSize: '0.75rem',
		textAlign: 'center',
		whiteSpace: 'nowrap',
	},
	'.chord-search-field input': {
		boxSizing: 'border-box',
		width: '100%',
		minHeight: '1.9rem',
		padding: '0.3rem 0.5rem',
		border: 'none',
		outline: 'none',
		backgroundColor: 'transparent',
		color: 'inherit',
		font: 'inherit',
	},
	'.chord-search-input-with-options': {
		display: 'flex',
		alignItems: 'center',
		gap: '0.1rem',
		paddingRight: '0.15rem',
	},
	'.chord-search-input-with-options input': {
		minWidth: '0',
		border: 'none',
		outline: 'none',
		backgroundColor: 'transparent',
		paddingRight: '0.2rem',
	},
	'.chord-search-input-with-options .chord-search-option': {
		minWidth: '1.6rem',
		minHeight: '1.6rem',
		zIndex: '2',
		padding: '0.1rem',
		border: 'none',
		backgroundColor: 'transparent',
		fontSize: '0.7rem',
	},
	'.chord-search-button': {
		minHeight: '1.9rem',
		minWidth: '1.9rem',
		padding: '0.2rem 0.45rem',
		border: '1px solid var(--color-neutral-300, #d4d4d8)',
		borderRadius: '0.35rem',
		backgroundColor: 'var(--color-neutral-50, #fafafa)',
		color: 'inherit',
		font: 'inherit',
		cursor: 'pointer',
	},
	'.chord-search-button:hover': {
		backgroundColor: 'var(--color-neutral-100, #f4f4f5)',
	},
	'.chord-search-toggle-replace, .chord-search-previous, .chord-search-next, .chord-search-close': {
		border: 'none',
		backgroundColor: 'transparent',
	},
	'.chord-search-toggle-replace:hover, .chord-search-previous:hover, .chord-search-next:hover, .chord-search-close:hover': {
		backgroundColor: 'var(--color-neutral-100, #f4f4f5)',
	},
	'.chord-search-close': {
		position: 'static',
		fontSize: '1.15rem',
		lineHeight: '1',
	},
	'.chord-search-options': {
		display: 'flex',
		flexWrap: 'wrap',
		gap: '0.8rem',
		color: 'var(--color-neutral-600, #52525b)',
	},
	'.chord-search-controls .chord-search-field': {
		minWidth: '0',
		flex: '1 1 auto',
	},
	'.chord-search-replace-row .chord-search-field': {
		minWidth: '0',
		flex: '1 1 auto',
	},
	'.chord-search-option': {
		display: 'inline-flex',
		alignItems: 'center',
		gap: '0.35rem',
		cursor: 'pointer',
	},
	'.chord-search-toggle': {
		minWidth: '2.25rem',
		justifyContent: 'center',
		fontWeight: '600',
	},
	'.chord-search-toggle input': {
		display: 'none',
	},
	'.chord-search-toggle.is-active': {
		borderColor: 'var(--color-primary-500, #3b82f6)',
		backgroundColor: 'var(--color-primary-100, #dbeafe)',
		color: 'var(--color-primary-700, #1d4ed8)',
	},
	'.cm-lintRange-info': {
		backgroundImage: 'url("data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="6" height="3"><path d="m0 2.5 l2 -1.5 l1 0 l2 1.5 l1 0" stroke="%23dc2626" fill="none" stroke-width="1"/></svg>") !important',
		backgroundSize: '6px 3px',
		backgroundPosition: 'left bottom',
		backgroundRepeat: 'repeat-x',
	},
	'.cm-lintRange-warning': {
		backgroundImage: 'url("data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="6" height="3"><path d="m0 2.5 l2 -1.5 l1 0 l2 1.5 l1 0" stroke="%23d97706" fill="none" stroke-width="1"/></svg>") !important',
		backgroundSize: '6px 3px',
		backgroundPosition: 'left bottom',
		backgroundRepeat: 'repeat-x',
	},
	'.cm-lintRange-error': {
		backgroundImage: 'url("data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="6" height="3"><path d="m0 2.5 l2 -1.5 l1 0 l2 1.5 l1 0" stroke="%23dc2626" fill="none" stroke-width="1"/></svg>") !important',
		backgroundSize: '6px 3px',
		backgroundPosition: 'left bottom',
		backgroundRepeat: 'repeat-x',
	},
});
